language: rust

rust:
  - stable
  - beta
  - nightly

jobs:
  allow_failures:
    - rust: nightly

script:
  - cargo test --no-default-features
#  - bash -c "! rustc -V | grep nightly || cargo bench --features benchmark --verbose"
